name: bovi_sales
description: "A new Flutter project."
publish_to: 'none' # Este proyecto no se publicará en pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/BoviSales(Onboarding).webp  # Asegúrate de que esta ruta sea correcta y que la imagen esté en esta ubicación
    - assets/images/BoviSales(Onboarding).jpg  # Asegúrate de que esta ruta sea correcta y que la imagen esté en esta ubicación
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
